plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
theme: jekyll-theme-dinky
title: Kilcreggan Garage
description: Local Family Run Business
show_downloads: false
logo: https://github.com/TheLastDestroyer/kilcreggangarage.github.io/blob/master/assets/images/logo.png?raw=true

defaults:
  - scope:
      path: "assets/images/slideshow"
    values:
      image: true
